spring.application.name=beu5w1d5
spring.datasource.url=jdbc:postgresql://localhost:5432/beu5w1d5
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace